name: SysMonService

on:
  push:
    branches: ["master"]
  pull_request:
    branches: ["master"]

jobs:
  build:
    if: |
      (github.event_name == 'push' && contains(github.event.head_commit.message, 'Version')) ||
      (github.event_name == 'pull_request' && contains(github.event.pull_request.title, 'Version'))    
    runs-on: self-hosted
    
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 9.0.x

      - name: Restore .NET
        run: dotnet restore

      - name: Publish .NET Service
        run: >
          dotnet publish -c Release -r win-x64 
          --self-contained true 
          -p:PublishSingleFile=true 
          -p:PublishTrimmed=false 
          -p:IncludeNativeLibrariesForSelfExtract=true 
          -p:DebugType=None 
          -o ./publish
      
      - name: Set up Python / PlatformIO
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install PlatformIO / Esptool
        run: |
          python -m pip install --upgrade pip
          pip install --upgrade platformio esptool
          
      - name: Build ESP32 Firmware
        run: |
          cd SysMonUI
          pio run

      - name: Upload All Artifacts to Gitea
        shell: powershell
        env:
          G_TOKEN: ${{ secrets.G_TOKEN }}
          REPO_OWNER: ${{ github.repository_owner }}
          SERVER_URL: "http://truenas.local:30008"
          COMMIT_MSG: ${{ github.event.head_commit.message }}
        run: |
          # 1. Versioning Logic [cite: 6]
          if ($env:COMMIT_MSG -match 'Version\s+([\d\.]+)') { $VERSION = $matches[1] } else { $VERSION = "0.0.0-manual" }
          $base_url = "$env:SERVER_URL/api/packages/$env:REPO_OWNER/generic/ESP32SystemMonitor/$VERSION"
          $headers = @{ "Authorization" = "Bearer $env:G_TOKEN" }
          
          # 2. Dynamic Discovery (Finds .NET 9 and Firmware regardless of exact path)
          $SERVICE_EXE = Get-ChildItem -Path "." -Filter "SysMonService.exe" -Recurse | Where-Object { $_.FullName -like "*publish*" } | Select-Object -First 1 -ExpandProperty FullName
          $BOOTLOADER = Get-ChildItem -Path "." -Filter "bootloader.bin" -Recurse | Select-Object -First 1 -ExpandProperty FullName
          $PARTITIONS = Get-ChildItem -Path "." -Filter "partitions.bin" -Recurse | Select-Object -First 1 -ExpandProperty FullName
          $FIRMWARE = Get-ChildItem -Path "." -Filter "firmware.bin" -Recurse | Select-Object -First 1 -ExpandProperty FullName

          # 3. Upload Service
          if ($SERVICE_EXE) {
              Write-Host "Uploading Service: $SERVICE_EXE"
              Invoke-RestMethod -Uri "$base_url/SysMonService.exe" -Method Put -InFile $SERVICE_EXE -Headers $headers
          }

          # 4. Upload Firmware Trifecta 
          Write-Host "Uploading Firmware Parts..."
          Invoke-RestMethod -Uri "$base_url/bootloader.bin" -Method Put -InFile $BOOTLOADER -Headers $headers
          Invoke-RestMethod -Uri "$base_url/partitions.bin" -Method Put -InFile $PARTITIONS -Headers $headers
          Invoke-RestMethod -Uri "$base_url/firmware.bin" -Method Put -InFile $FIRMWARE -Headers $headers