// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.0
// LVGL version: 8.3.11
// Project name: SquareLine_Project

#ifndef _SQUARELINE_PROJECT_UI_H
#define _SQUARELINE_PROJECT_UI_H

#ifdef __cplusplus
extern "C" {
#endif

#include "lvgl.h"

#include "ui_helpers.h"
#include "ui_events.h"


///////////////////// SCREENS ////////////////////

#include "screens/ui_Home.h"

///////////////////// VARIABLES ////////////////////


// EVENTS

extern lv_obj_t * ui____initial_actions0;

// IMAGES AND IMAGE SETS
LV_IMG_DECLARE(ui_img_842386787);    // assets/microchip-solid-full.png
LV_IMG_DECLARE(ui_img_794451024);    // assets/memory-solid-full.png
LV_IMG_DECLARE(ui_img_1133614182);    // assets/image-solid-full.png
LV_IMG_DECLARE(ui_img_1763518677);    // assets/network-wired-solid-full.png

// FONTS
LV_FONT_DECLARE(ui_font_FontAwesome);

// UI INIT
void ui_init(void);
void ui_destroy(void);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
