// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.0
// LVGL version: 8.3.11
// Project name: SquareLine_Project

#include "../ui.h"

lv_obj_t * ui_Home = NULL;
lv_obj_t * ui_PnlProcessor = NULL;
lv_obj_t * ui_PnlMemory = NULL;
lv_obj_t * ui_PnlGraphics = NULL;
lv_obj_t * ui_PnlNetwork = NULL;
lv_obj_t * ui_ImgProcessor = NULL;
lv_obj_t * ui_ImgMemory = NULL;
lv_obj_t * ui_ImgGraphics = NULL;
lv_obj_t * ui_ImgNetwork = NULL;
lv_obj_t * ui_LblProcessorPct = NULL;
lv_obj_t * ui_LblProcessorClock = NULL;
lv_obj_t * ui_LblProcessorTemp = NULL;
lv_obj_t * ui_LblMemoryUsage = NULL;
lv_obj_t * ui_LblGraphicsPct = NULL;
lv_obj_t * ui_LblGraphicsClock = NULL;
lv_obj_t * ui_LblGraphicsTemp = NULL;
lv_obj_t * ui_ChartNetUp = NULL;
lv_obj_t * ui_ChartNetDown = NULL;
lv_obj_t * ui_LblNetworkDownUp = NULL;
lv_obj_t * ui_TxtDownload = NULL;
lv_obj_t * ui_TxtUpload = NULL;

lv_chart_series_t * ui_chart_series_net_up = NULL;
lv_chart_series_t * ui_chart_series_net_down = NULL;

// event funtions

// build funtions

void ui_Home_screen_init(void)
{
    ui_Home = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_Home, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_Home, lv_color_hex(0x727272), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Home, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_PnlProcessor = lv_obj_create(ui_Home);
    lv_obj_set_width(ui_PnlProcessor, 155);
    lv_obj_set_height(ui_PnlProcessor, 115);
    lv_obj_set_x(ui_PnlProcessor, -79);
    lv_obj_set_y(ui_PnlProcessor, -60);
    lv_obj_set_align(ui_PnlProcessor, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_PnlProcessor, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_PnlProcessor, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_PnlProcessor, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_PnlMemory = lv_obj_create(ui_Home);
    lv_obj_set_width(ui_PnlMemory, 155);
    lv_obj_set_height(ui_PnlMemory, 40);
    lv_obj_set_x(ui_PnlMemory, 79);
    lv_obj_set_y(ui_PnlMemory, -97);
    lv_obj_set_align(ui_PnlMemory, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_PnlMemory, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_PnlMemory, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_PnlMemory, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_PnlGraphics = lv_obj_create(ui_Home);
    lv_obj_set_width(ui_PnlGraphics, 155);
    lv_obj_set_height(ui_PnlGraphics, 115);
    lv_obj_set_x(ui_PnlGraphics, -80);
    lv_obj_set_y(ui_PnlGraphics, 58);
    lv_obj_set_align(ui_PnlGraphics, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_PnlGraphics, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_PnlGraphics, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_PnlGraphics, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_PnlNetwork = lv_obj_create(ui_Home);
    lv_obj_set_width(ui_PnlNetwork, 155);
    lv_obj_set_height(ui_PnlNetwork, 189);
    lv_obj_set_x(ui_PnlNetwork, 79);
    lv_obj_set_y(ui_PnlNetwork, 22);
    lv_obj_set_align(ui_PnlNetwork, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_PnlNetwork, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_PnlNetwork, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_PnlNetwork, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_ImgProcessor = lv_img_create(ui_Home);
    lv_img_set_src(ui_ImgProcessor, &ui_img_842386787);
    lv_obj_set_width(ui_ImgProcessor, LV_SIZE_CONTENT);   /// 30
    lv_obj_set_height(ui_ImgProcessor, LV_SIZE_CONTENT);    /// 30
    lv_obj_set_x(ui_ImgProcessor, -137);
    lv_obj_set_y(ui_ImgProcessor, -97);
    lv_obj_set_align(ui_ImgProcessor, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_ImgProcessor, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_ImgProcessor, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_ImgMemory = lv_img_create(ui_Home);
    lv_img_set_src(ui_ImgMemory, &ui_img_794451024);
    lv_obj_set_width(ui_ImgMemory, LV_SIZE_CONTENT);   /// 30
    lv_obj_set_height(ui_ImgMemory, LV_SIZE_CONTENT);    /// 30
    lv_obj_set_x(ui_ImgMemory, 22);
    lv_obj_set_y(ui_ImgMemory, -97);
    lv_obj_set_align(ui_ImgMemory, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_ImgMemory, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_ImgMemory, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_ImgGraphics = lv_img_create(ui_Home);
    lv_img_set_src(ui_ImgGraphics, &ui_img_1133614182);
    lv_obj_set_width(ui_ImgGraphics, LV_SIZE_CONTENT);   /// 30
    lv_obj_set_height(ui_ImgGraphics, LV_SIZE_CONTENT);    /// 30
    lv_obj_set_x(ui_ImgGraphics, -137);
    lv_obj_set_y(ui_ImgGraphics, 22);
    lv_obj_set_align(ui_ImgGraphics, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_ImgGraphics, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_ImgGraphics, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_ImgNetwork = lv_img_create(ui_Home);
    lv_img_set_src(ui_ImgNetwork, &ui_img_1763518677);
    lv_obj_set_width(ui_ImgNetwork, LV_SIZE_CONTENT);   /// 30
    lv_obj_set_height(ui_ImgNetwork, LV_SIZE_CONTENT);    /// 30
    lv_obj_set_x(ui_ImgNetwork, 22);
    lv_obj_set_y(ui_ImgNetwork, -52);
    lv_obj_set_align(ui_ImgNetwork, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_ImgNetwork, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_ImgNetwork, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_LblProcessorPct = lv_label_create(ui_Home);
    printf(">>> UI_FILE: Label created at address: %p\n", (void*)ui_LblProcessorPct);    lv_obj_set_width(ui_LblProcessorPct, 100);
    lv_obj_set_height(ui_LblProcessorPct, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_LblProcessorPct, -62);
    lv_obj_set_y(ui_LblProcessorPct, -98);
    lv_obj_set_align(ui_LblProcessorPct, LV_ALIGN_CENTER);
    lv_label_set_text(ui_LblProcessorPct, "- %");
    lv_obj_set_style_text_color(ui_LblProcessorPct, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_LblProcessorPct, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_LblProcessorPct, LV_TEXT_ALIGN_LEFT, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_LblProcessorPct, &lv_font_montserrat_20, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_LblProcessorClock = lv_label_create(ui_Home);
    lv_obj_set_width(ui_LblProcessorClock, 100);
    lv_obj_set_height(ui_LblProcessorClock, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_LblProcessorClock, -62);
    lv_obj_set_y(ui_LblProcessorClock, -65);
    lv_obj_set_align(ui_LblProcessorClock, LV_ALIGN_CENTER);
    lv_label_set_text(ui_LblProcessorClock, "- GHz");
    lv_obj_set_style_text_color(ui_LblProcessorClock, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_LblProcessorClock, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_LblProcessorClock, LV_TEXT_ALIGN_LEFT, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_LblProcessorClock, &lv_font_montserrat_20, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_LblProcessorTemp = lv_label_create(ui_Home);
    lv_obj_set_width(ui_LblProcessorTemp, 100);
    lv_obj_set_height(ui_LblProcessorTemp, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_LblProcessorTemp, -62);
    lv_obj_set_y(ui_LblProcessorTemp, -32);
    lv_obj_set_align(ui_LblProcessorTemp, LV_ALIGN_CENTER);
    lv_label_set_text(ui_LblProcessorTemp, "- °c");
    lv_obj_set_style_text_color(ui_LblProcessorTemp, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_LblProcessorTemp, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_LblProcessorTemp, LV_TEXT_ALIGN_LEFT, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_LblProcessorTemp, &lv_font_montserrat_20, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_LblMemoryUsage = lv_label_create(ui_Home);
    lv_obj_set_width(ui_LblMemoryUsage, 100);
    lv_obj_set_height(ui_LblMemoryUsage, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_LblMemoryUsage, 97);
    lv_obj_set_y(ui_LblMemoryUsage, -98);
    lv_obj_set_align(ui_LblMemoryUsage, LV_ALIGN_CENTER);
    lv_label_set_text(ui_LblMemoryUsage, "- GB");
    lv_obj_set_style_text_color(ui_LblMemoryUsage, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_LblMemoryUsage, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_LblMemoryUsage, LV_TEXT_ALIGN_LEFT, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_LblMemoryUsage, &lv_font_montserrat_20, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_LblGraphicsPct = lv_label_create(ui_Home);
    lv_obj_set_width(ui_LblGraphicsPct, 100);
    lv_obj_set_height(ui_LblGraphicsPct, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_LblGraphicsPct, -62);
    lv_obj_set_y(ui_LblGraphicsPct, 21);
    lv_obj_set_align(ui_LblGraphicsPct, LV_ALIGN_CENTER);
    lv_label_set_text(ui_LblGraphicsPct, "- %");
    lv_obj_set_style_text_color(ui_LblGraphicsPct, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_LblGraphicsPct, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_LblGraphicsPct, LV_TEXT_ALIGN_LEFT, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_LblGraphicsPct, &lv_font_montserrat_20, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_LblGraphicsClock = lv_label_create(ui_Home);
    lv_obj_set_width(ui_LblGraphicsClock, 100);
    lv_obj_set_height(ui_LblGraphicsClock, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_LblGraphicsClock, -62);
    lv_obj_set_y(ui_LblGraphicsClock, 54);
    lv_obj_set_align(ui_LblGraphicsClock, LV_ALIGN_CENTER);
    lv_label_set_text(ui_LblGraphicsClock, "- MHz");
    lv_obj_set_style_text_color(ui_LblGraphicsClock, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_LblGraphicsClock, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_LblGraphicsClock, LV_TEXT_ALIGN_LEFT, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_LblGraphicsClock, &lv_font_montserrat_20, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_LblGraphicsTemp = lv_label_create(ui_Home);
    lv_obj_set_width(ui_LblGraphicsTemp, 100);
    lv_obj_set_height(ui_LblGraphicsTemp, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_LblGraphicsTemp, -62);
    lv_obj_set_y(ui_LblGraphicsTemp, 87);
    lv_obj_set_align(ui_LblGraphicsTemp, LV_ALIGN_CENTER);
    lv_label_set_text(ui_LblGraphicsTemp, "- °c");
    lv_obj_set_style_text_color(ui_LblGraphicsTemp, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_LblGraphicsTemp, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_LblGraphicsTemp, LV_TEXT_ALIGN_LEFT, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_LblGraphicsTemp, &lv_font_montserrat_20, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_ChartNetUp = lv_chart_create(ui_Home);
    lv_obj_set_width(ui_ChartNetUp, 145);
    lv_obj_set_height(ui_ChartNetUp, 47);
    lv_obj_set_x(ui_ChartNetUp, 79);
    lv_obj_set_y(ui_ChartNetUp, 80);
    lv_obj_set_align(ui_ChartNetUp, LV_ALIGN_CENTER);
    lv_chart_set_type(ui_ChartNetUp, LV_CHART_TYPE_LINE);
    lv_chart_set_axis_tick(ui_ChartNetUp, LV_CHART_AXIS_PRIMARY_X, 10, 5, 0, 0, false, 50);
    lv_chart_set_axis_tick(ui_ChartNetUp, LV_CHART_AXIS_PRIMARY_Y, 10, 5, 0, 0, false, 50);
    lv_chart_set_axis_tick(ui_ChartNetUp, LV_CHART_AXIS_SECONDARY_Y, 10, 5, 0, 0, false, 25);
    ui_chart_series_net_up = lv_chart_add_series(ui_ChartNetUp, lv_color_hex(0x808080),
                                                                     LV_CHART_AXIS_PRIMARY_Y);
    lv_obj_set_style_bg_color(ui_ChartNetUp, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_ChartNetUp, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_ChartNetDown = lv_chart_create(ui_Home);
    lv_obj_set_width(ui_ChartNetDown, 145);
    lv_obj_set_height(ui_ChartNetDown, 47);
    lv_obj_set_x(ui_ChartNetDown, 79);
    lv_obj_set_y(ui_ChartNetDown, 12);
    lv_obj_set_align(ui_ChartNetDown, LV_ALIGN_CENTER);
    lv_chart_set_type(ui_ChartNetDown, LV_CHART_TYPE_LINE);
    lv_chart_set_axis_tick(ui_ChartNetDown, LV_CHART_AXIS_PRIMARY_X, 10, 5, 0, 0, false, 50);
    lv_chart_set_axis_tick(ui_ChartNetDown, LV_CHART_AXIS_PRIMARY_Y, 10, 5, 0, 0, false, 50);
    lv_chart_set_axis_tick(ui_ChartNetDown, LV_CHART_AXIS_SECONDARY_Y, 10, 5, 0, 0, false, 25);
    ui_chart_series_net_down = lv_chart_add_series(ui_ChartNetDown, lv_color_hex(0x808080),
                                                                       LV_CHART_AXIS_PRIMARY_Y);
    lv_obj_set_style_bg_color(ui_ChartNetDown, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_ChartNetDown, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_LblNetworkDownUp = lv_label_create(ui_Home);
    lv_obj_set_width(ui_LblNetworkDownUp, 100);
    lv_obj_set_height(ui_LblNetworkDownUp, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_LblNetworkDownUp, 97);
    lv_obj_set_y(ui_LblNetworkDownUp, -53);
    lv_obj_set_align(ui_LblNetworkDownUp, LV_ALIGN_CENTER);
    lv_label_set_text(ui_LblNetworkDownUp, "- / -\n(MBps)");
    lv_obj_set_style_text_color(ui_LblNetworkDownUp, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_LblNetworkDownUp, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_LblNetworkDownUp, LV_TEXT_ALIGN_LEFT, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_LblNetworkDownUp, &lv_font_montserrat_10, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_TxtDownload = lv_label_create(ui_Home);
    lv_obj_set_width(ui_TxtDownload, 100);
    lv_obj_set_height(ui_TxtDownload, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_TxtDownload, 58);
    lv_obj_set_y(ui_TxtDownload, -19);
    lv_obj_set_align(ui_TxtDownload, LV_ALIGN_CENTER);
    lv_label_set_text(ui_TxtDownload, "Download");
    lv_obj_set_style_text_color(ui_TxtDownload, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_TxtDownload, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_TxtDownload, LV_TEXT_ALIGN_LEFT, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_TxtDownload, &lv_font_montserrat_10, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_TxtUpload = lv_label_create(ui_Home);
    lv_obj_set_width(ui_TxtUpload, 100);
    lv_obj_set_height(ui_TxtUpload, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_TxtUpload, 58);
    lv_obj_set_y(ui_TxtUpload, 56);
    lv_obj_set_align(ui_TxtUpload, LV_ALIGN_CENTER);
    lv_label_set_text(ui_TxtUpload, "Upload\n");
    lv_obj_set_style_text_color(ui_TxtUpload, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_TxtUpload, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_TxtUpload, LV_TEXT_ALIGN_LEFT, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_TxtUpload, &lv_font_montserrat_10, LV_PART_MAIN | LV_STATE_DEFAULT);

}

void ui_Home_screen_destroy(void)
{
    if(ui_Home) lv_obj_del(ui_Home);

    // NULL screen variables
    ui_Home = NULL;
    ui_PnlProcessor = NULL;
    ui_PnlMemory = NULL;
    ui_PnlGraphics = NULL;
    ui_PnlNetwork = NULL;
    ui_ImgProcessor = NULL;
    ui_ImgMemory = NULL;
    ui_ImgGraphics = NULL;
    ui_ImgNetwork = NULL;
    ui_LblProcessorPct = NULL;
    ui_LblProcessorClock = NULL;
    ui_LblProcessorTemp = NULL;
    ui_LblMemoryUsage = NULL;
    ui_LblGraphicsPct = NULL;
    ui_LblGraphicsClock = NULL;
    ui_LblGraphicsTemp = NULL;
    ui_ChartNetUp = NULL;
    ui_ChartNetDown = NULL;
    ui_LblNetworkDownUp = NULL;
    ui_TxtDownload = NULL;
    ui_TxtUpload = NULL;

}
