// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.0
// LVGL version: 8.3.11
// Project name: SquareLine_Project

#ifndef UI_HOME_H
#define UI_HOME_H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_Home
extern void ui_Home_screen_init(void);
extern void ui_Home_screen_destroy(void);
extern lv_obj_t * ui_Home;
extern lv_obj_t * ui_PnlProcessor;
extern lv_obj_t * ui_PnlMemory;
extern lv_obj_t * ui_PnlGraphics;
extern lv_obj_t * ui_PnlNetwork;
extern lv_obj_t * ui_ImgProcessor;
extern lv_obj_t * ui_ImgMemory;
extern lv_obj_t * ui_ImgGraphics;
extern lv_obj_t * ui_ImgNetwork;
extern lv_obj_t * ui_LblProcessorPct;
extern lv_obj_t * ui_LblProcessorClock;
extern lv_obj_t * ui_LblProcessorTemp;
extern lv_obj_t * ui_LblMemoryUsage;
extern lv_obj_t * ui_LblGraphicsPct;
extern lv_obj_t * ui_LblGraphicsClock;
extern lv_obj_t * ui_LblGraphicsTemp;
extern lv_obj_t * ui_ChartNetUp;
extern lv_obj_t * ui_ChartNetDown;
extern lv_obj_t * ui_LblNetworkDownUp;
extern lv_obj_t * ui_TxtDownload;
extern lv_obj_t * ui_TxtUpload;
extern lv_chart_series_t * ui_chart_series_net_up;
extern lv_chart_series_t * ui_chart_series_net_down;
// CUSTOM VARIABLES

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif

